# API Keys
ANTHROPIC_API_KEY=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
OPENAI_API_KEY=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
ALPHA_VANTAGE_API_KEY=L57Y9MVDFO54KO1O
FINANCIAL_DATASETS_API_KEY=c93a9274-4183-446e-a9e1-6befeba1003b  # Financial Datasets MCP API key
POLYGON_API_KEY=P2fNqZwaNTc1i44TjwC8HaaslgsTPO7z
NEWSAPI_KEY=dc7e45b52c024ffb8138d53e1c92094c
FRED_API_KEY=18860d2ba3497510e11bf4097c4e7d5b

# Broker API Keys (Alpaca) - Paper Trading
# Get free API keys at: https://alpaca.markets/
# Sign up for a free account and get paper trading API keys

# DEE-BOT Paper Trading API (Account 1)
ALPACA_API_KEY_DEE=PKLW68W7RZJFTXV8LJO8
ALPACA_SECRET_KEY_DEE=HV3epwO5AqhqNQEiv3piSOVGD40ly0rW98whdGMv

# DEE-BOT (primary variables used by trading scripts)
ALPACA_API_KEY=PKLW68W7RZJFTXV8LJO8
ALPACA_SECRET_KEY=HV3epwO5AqhqNQEiv3piSOVGD40ly0rW98whdGMv
ALPACA_BASE_URL=https://paper-api.alpaca.markets

# SHORGAN-BOT Paper Trading API (Account 2)
ALPACA_API_KEY_SHORGAN=PKDNSGIY71EZGG40EHOV
ALPACA_SECRET_KEY_SHORGAN=Z0Kz1Ay7K9uXSkXomVRxl8BavEGqsfiv3qQvLhx9

# Default/Active Bot Configuration (Currently using DEE-BOT)
APCA_API_KEY_ID=PK6FZK4DAQVTD7DYVH78
APCA_API_SECRET_KEY=JKHXnsi4GeZV5GiA06kGyMhRrvrfEjOzw5X7bHBt
APCA_API_BASE_URL=https://paper-api.alpaca.markets/

# Optional API Keys
TWITTER_API_KEY=yhxUpQoaXxcEncBUEi1L7cAFyw
TWITTER_API_SECRET=RF2ytLXhWqOB01s77fvIWFwI0NH6bY3DAFwLKq1cxKU8hGhTm5
TWITTER_ACCESS_TOKEN=1892517799664230400-VzA12HQDIEUgWEfiIOPCAh5sGuyc7d
TWITTER_ACCESS_SECRET=ylcmXXK28LQjc6VAPjlebink5qxJRuBVp47hdH36lE1PmK
REDDIT_CLIENT_ID=TMiptjB1iV-UHthKL1TAsQ
REDDIT_CLIENT_SECRET=WIHgfjLVn0emj_Av8uB0Ugj-OF05Jw
REDDIT_USER_AGENT=shorgan-bot/ by Legitimate_Road_3380

# Database Configuration
DATABASE_URL=sqlite:///trading_bot.db
REDIS_URL=redis://localhost:6379/0

# Trading Configuration
ENVIRONMENT=development  # development, staging, production
TRADING_MODE=paper  # paper, live
DEFAULT_PORTFOLIO_VALUE=100000
MAX_PORTFOLIO_RISK=0.05
MAX_POSITION_SIZE=0.20

# Risk Management
RISK_PROFILE=aggressive  # aggressive, neutral, conservative
MAX_DAILY_LOSS=0.05
MAX_DRAWDOWN=0.20
VAR_CONFIDENCE=0.95

# Agent Configuration
DEBATE_ROUNDS=3
MIN_CONSENSUS_THRESHOLD=0.6
AGENT_TIMEOUT_SECONDS=30

# API Settings
API_PORT=8000
API_HOST=0.0.0.0
CORS_ORIGINS=["http://localhost:3000", "http://localhost:8080"]

# Monitoring
PROMETHEUS_PORT=9090
LOG_LEVEL=INFO  # DEBUG, INFO, WARNING, ERROR
LOG_FILE=logs/trading_bot.log

# Backtesting
BACKTEST_START_DATE=2020-01-01
BACKTEST_END_DATE=2023-12-31
BACKTEST_INITIAL_CAPITAL=100000
BACKTEST_COMMISSION=0.001

# Market Data
MARKET_DATA_PROVIDER=yfinance  # yfinance, alpha_vantage, polygon
DATA_UPDATE_INTERVAL=60  # seconds
HISTORICAL_DATA_YEARS=5

# Notification Settings
# Get Telegram bot token from @BotFather on Telegram
# Get chat ID by messaging your bot and checking https://api.telegram.org/bot<YOUR_BOT_TOKEN>/getUpdates
TELEGRAM_BOT_TOKEN=8093845586:AAEqytNDQ_dVzVp6ZbDyveMTx7MZMtG6N0c
TELEGRAM_CHAT_ID=7870288896

# Feature Flags
ENABLE_LIVE_TRADING=false
ENABLE_NOTIFICATIONS=true
ENABLE_AUTO_REBALANCING=false
ENABLE_SENTIMENT_ANALYSIS=true
ENABLE_NEWS_ANALYSIS=true