environment: production
feature_flags:
  multi_agent_system: true
  bull_bear_debates: true
  alternative_data: true
  monte_carlo_backtest: true
  kelly_position_sizing: true
  portfolio_attribution: true
  health_monitoring: true
  telegram_notifications: true
  email_notifications: true
trading:
  mode: paper
  bots:
    dee_bot:
      enabled: true
      allocation_pct: 50
    shorgan_bot:
      enabled: true
      allocation_pct: 50
  execution:
    market_hours_only: true
    pre_market_start: 04:00
    market_open: 09:30
    market_close: '16:00'
    after_hours_end: '20:00'
    order_defaults:
      time_in_force: day
      extended_hours: false
  risk_limits:
    max_daily_loss_pct: 0.02
    max_drawdown_pct: 0.1
    position_concentration_limit: 0.2
    sector_concentration_limit: 0.3
  portfolio_size: 2000000
pipeline:
  daily_schedule:
    data_collection:
      start_time: 06:00
      duration_minutes: 15
    agent_analysis:
      start_time: 06:15
      duration_minutes: 30
      phases:
      - fundamental_analysis
      - technical_analysis
      - sentiment_analysis
      - news_analysis
      - alternative_data
    debate_phase:
      start_time: 06:45
      duration_minutes: 15
      min_confidence_for_debate: 0.6
    strategy_allocation:
      start_time: 07:00
      duration_minutes: 15
    report_generation:
      start_time: 07:15
      duration_minutes: 15
    notifications:
      start_time: 07:30
      duration_minutes: 5
    trade_execution:
      start_time: 09:30
      pre_market_validation: 09:15
  monitoring:
    health_check_interval_minutes: 30
    position_check_interval_minutes: 15
    alert_check_interval_minutes: 5
agents:
  enabled: true
  consensus:
    min_agents_required: 5
    approval_threshold: 0.55
    debate_threshold: 0.6
  weights:
    fundamental_analyst: 0.2
    technical_analyst: 0.15
    news_analyst: 0.15
    sentiment_analyst: 0.1
    alternative_data: 0.1
    bull_researcher: 0.15
    bear_researcher: 0.15
  individual_agents:
    fundamental_analyst:
      enabled: true
      data_sources:
      - financial_datasets
      - yahoo_finance
      min_metrics_required: 10
    technical_analyst:
      enabled: true
      indicators:
      - rsi
      - macd
      - bollinger_bands
      - volume_profile
      - support_resistance
    news_analyst:
      enabled: true
      sources:
      - financial_datasets_news
      - newsapi
      sentiment_threshold: 0.3
    sentiment_analyst:
      enabled: true
      sources:
      - reddit
      - twitter
      - stocktwits
    alternative_data:
      enabled: true
      sources:
      - options_flow
      - dark_pool
      - insider_trading
    bull_researcher:
      enabled: true
      focus: upside_catalysts
    bear_researcher:
      enabled: true
      focus: downside_risks
data_sources:
  financial_datasets:
    enabled: true
    api_base_url: https://api.financialdatasets.ai
    rate_limit_per_minute: 60
    cache_duration_hours: 4
  alpaca:
    enabled: true
    api_version: v2
    data_feed: iex
  yahoo_finance:
    enabled: true
    fallback_only: true
  newsapi:
    enabled: true
    categories:
    - business
    - technology
    max_articles_per_query: 100
  reddit:
    enabled: true
    subreddits:
    - wallstreetbets
    - stocks
    - investing
    min_upvotes: 50
alerts:
  channels:
    telegram:
      enabled: true
      priority_levels:
      - critical
      - high
      - medium
    email:
      enabled: true
      priority_levels:
      - critical
      - high
    slack:
      enabled: false
  notification_schedule:
    morning_report: 07:30
    mid_day_update: '12:00'
    close_report: '16:15'
    evening_summary: '18:00'
  alert_triggers:
    position_loss_pct: 0.05
    position_gain_pct: 0.1
    portfolio_loss_pct: 0.02
    execution_failure: true
    api_error: true
    data_source_failure: true
monitoring:
  health_checks:
    enabled: true
    interval_minutes: 30
    checks:
    - api_connectivity
    - data_freshness
    - disk_space
    - memory_usage
    - position_sync
  performance_tracking:
    enabled: true
    metrics:
    - daily_pnl
    - win_rate
    - sharpe_ratio
    - max_drawdown
    - position_count
    - execution_rate
  logging:
    level: INFO
    rotation: daily
    retention_days: 90
    destinations:
    - file
    - console
reports:
  daily:
    enabled: true
    generation_time: 07:15
    formats:
    - markdown
    - pdf
    - json
    include_sections:
    - market_overview
    - agent_recommendations
    - consensus_decisions
    - risk_metrics
    - execution_plan
  weekly:
    enabled: true
    generation_day: friday
    generation_time: '17:00'
  monthly:
    enabled: true
    generation_day: last
    generation_time: '17:00'
  distribution:
    telegram: true
    email: true
    archive: true
backtesting:
  enabled: true
  historical_data_years: 2
  monte_carlo_simulations: 1000
  confidence_intervals:
  - 0.5
  - 0.75
  - 0.95
system:
  timezone: America/New_York
  concurrency:
    max_workers: 10
    async_enabled: true
  caching:
    enabled: true
    backend: redis
    default_ttl_seconds: 3600
  database:
    type: sqlite
    path: data/trading_bot.db
    backup_enabled: true
    backup_interval_hours: 24
  security:
    api_key_rotation_days: 90
    encrypt_credentials: true
    audit_logging: true
  emergency:
    kill_switch_enabled: true
    auto_close_on_error: false
    max_consecutive_errors: 5
