name: Code Quality

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install security tools
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety

    - name: Run Bandit security checks
      run: |
        bandit -r agents/ scripts-and-data/automation/ -ll -f json -o bandit-report.json || true
        bandit -r agents/ scripts-and-data/automation/ -ll

    - name: Check for known vulnerabilities
      run: |
        safety check --json || true
        safety check

    - name: Upload Bandit report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: bandit-security-report
        path: bandit-report.json

  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - uses: actions/checkout@v4

    - name: Dependency Review
      uses: actions/dependency-review-action@v3

  complexity:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install complexity tools
      run: |
        python -m pip install --upgrade pip
        pip install radon mccabe

    - name: Check code complexity
      run: |
        echo "=== Cyclomatic Complexity ==="
        radon cc agents/ scripts-and-data/automation/ -s -a
        echo ""
        echo "=== Maintainability Index ==="
        radon mi agents/ scripts-and-data/automation/ -s

  documentation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check for documentation
      run: |
        echo "Checking for README..."
        test -f README.md && echo "✅ README.md exists"

        echo "Checking for CONTRIBUTING..."
        test -f CONTRIBUTING.md && echo "✅ CONTRIBUTING.md exists"

        echo "Checking for CHANGELOG..."
        test -f CHANGELOG.md && echo "✅ CHANGELOG.md exists"

        echo "Checking for LICENSE..."
        test -f LICENSE && echo "✅ LICENSE exists" || echo "⚠️  LICENSE missing"

    - name: Check documentation quality
      run: |
        # Count markdown files
        echo "Documentation files: $(find docs -name '*.md' | wc -l)"

        # Check for broken links (basic check)
        echo "Checking for common documentation issues..."
        grep -r "TODO" docs/ --include="*.md" || echo "No TODOs found in docs"
